### ISSUE TITLE
Broken URL for app testing.

### ISSUE THREAD

**Issue by ctorres-nearsoft** [Nearsoft/nearbooks-android#48]
I became a tester for the app, but as soon as I tried to download it, I got this error message **"We're sorry, the requested URL was not found on this server."**

**Comment by epool** [comment]
It takes a couple of minutes for allowing you to download the app. Please tell me if you still getting problems with the url or if you have already downloaded the app. Thanks

**Comment by ctorres-nearsoft** [comment]
You are right, I already downloaded it :smile: thanks!

**Comment by epool** [comment]
nice! =p
